### ISSUE TITLE
Replacement for Craft 3

### ISSUE THREAD

**Issue by karensg** [nfourtythree/SecureAssetDownload#10]
Hey,

I found this plugin in a site I inherited. Do you have any recommendations how to replace this plugin in Craft 3?

Thanks!

**Comment by nfourtythree** [comment]
Hi @karensg 

I am not sure which would suit your needs best, but it looks like there are options on the [plugin store](https://plugins.craftcms.com/search?q=asset)

I think potentially [Digital Download](https://plugins.craftcms.com/digital-download) and [Protected Links](https://plugins.craftcms.com/protectedlinks) might be options.

Thanks.

**Comment by karensg** [comment]
Thank you! Will take a look at both of them.
