### ISSUE TITLE
How do I get asset id?

### ISSUE THREAD

**Issue by subratom** [nfourtythree/SecureAssetDownload#3]
I am generating download URLs for the content. Assets are embedded inside of content, how do I get asset id from the file name?

**Comment by nfourtythree** [comment]
Although the functionality at the moment doesn't cater for being passed a filename (although that is a good idea), you can get the ID of an asset in template tags by doing the following

``` twig
{% set assetId = craft.assets({ filename: "my-filename.txt" }).first().id %}
```

**Comment by subratom** [comment]
Thank you that worked!
