### ISSUE TITLE
Sources w/subfolders

### ISSUE THREAD

**Issue by heggerud** [nfourtythree/SecureAssetDownload#4]
SecureAssetDownloadService::serveAsset#56:
`$path = $this->_asset->source->sourceType->getBasePath().$this->_asset->filename;`

This doesn't work with subfolders. Fix:

```
$sourcePath = $this->_asset->source->sourceType->getBasePath();
$folderPath = $this->_asset->getFolder()->path;
$path = $sourcePath.$folderPath.$this->_asset->filename;
```

Thanks for the plugin, though - no point in reinventing the wheel ;)

**Comment by nfourtythree** [comment]
Thanks @heggerud great spot. Have just put your change in!

Cheers,
Nathaniel
