### ISSUE TITLE
Users in multiple groups cannot access file

### ISSUE THREAD

**Issue by admench** [nfourtythree/SecureAssetDownload#9]
Hi, thanks for this great plugin, I have the following issue:

A file has been set to be accessible by user groups: `[1, 5, 4, 8, 6, 7]`. A user who is in groups `9` and `1` cannot access this file, they get this:

![screen shot 2017-06-30 at 14 25 24](https://user-images.githubusercontent.com/672916/27737405-fc77751c-5d9f-11e7-8f2f-7d3653ea2f18.png)

Is there a restriction if a user is in _other groups_ than the one specified in the array?

**Comment by nfourtythree** [comment]
Hi @admench 

Thanks for highlighting this, I will have a look into it. Apologies for the delay in response I didn't see this issue come in!

Thanks,
Nathaniel

**Comment by nfourtythree** [comment]
Hi @admench 

I have just pushed a release that should sort this issue for you.

Let me know how you get on!
